import {
	Activity,
	Ambulance,
	Apple,
	Ban,
	Bandage,
	BatteryLow,
	Bed,
	Bike,
	Biohazard,
	Bone,
	Brain,
	Bug,
	Calendar,
	Candy,
	Carrot,
	CigaretteOff,
	CircleCheck,
	CircleHelp,
	CircleX,
	Clock,
	Coffee,
	Dna,
	Droplet,
	Dumbbell,
	Ear,
	Egg,
	Eye,
	Fish,
	Flame,
	Footprints,
	GlassWater,
	HandHeart,
	Heart,
	HeartPulse,
	Hospital,
	Leaf,
	Lightbulb,
	Microscope,
	Milk,
	Moon,
	PersonStanding,
	Pill,
	Salad,
	Scale,
	ShieldCheck,
	Smile,
	Snowflake,
	Soup,
	Sparkles,
	Stethoscope,
	Sun,
	Syringe,
	Tablets,
	Thermometer,
	Timer,
	TriangleAlert,
	Users,
	Utensils,
	Wheat,
	Wind,
	WineOff,
	Baby,
	Zap,
	type LucideIcon,
} from 'lucide-react';
import {ICON_ALIASES, type CuratedIconName, type IconName} from '../shared/icons';

export const ICON_COMPONENTS: Record<CuratedIconName, LucideIcon> = {
	'heart-pulse': HeartPulse,
	heart: Heart,
	brain: Brain,
	stethoscope: Stethoscope,
	pill: Pill,
	tablets: Tablets,
	syringe: Syringe,
	thermometer: Thermometer,
	droplet: Droplet,
	'glass-water': GlassWater,
	apple: Apple,
	salad: Salad,
	carrot: Carrot,
	fish: Fish,
	egg: Egg,
	milk: Milk,
	wheat: Wheat,
	candy: Candy,
	coffee: Coffee,
	utensils: Utensils,
	soup: Soup,
	baby: Baby,
	bone: Bone,
	eye: Eye,
	ear: Ear,
	'face-slightly-smiling': Smile,
	activity: Activity,
	'shield-check': ShieldCheck,
	moon: Moon,
	sun: Sun,
	bed: Bed,
	dumbbell: Dumbbell,
	footprints: Footprints,
	bike: Bike,
	'person-standing': PersonStanding,
	'cigarette-off': CigaretteOff,
	'wine-off': WineOff,
	scale: Scale,
	clock: Clock,
	timer: Timer,
	calendar: Calendar,
	'triangle-alert': TriangleAlert,
	ban: Ban,
	'circle-check': CircleCheck,
	'circle-x': CircleX,
	'circle-question-mark': CircleHelp,
	lightbulb: Lightbulb,
	microscope: Microscope,
	dna: Dna,
	bandage: Bandage,
	hospital: Hospital,
	ambulance: Ambulance,
	'hand-heart': HandHeart,
	users: Users,
	bug: Bug,
	biohazard: Biohazard,
	wind: Wind,
	leaf: Leaf,
	flame: Flame,
	snowflake: Snowflake,
	zap: Zap,
	'battery-low': BatteryLow,
	sparkles: Sparkles,
};

/** Built-in component for a curated icon (used when the icon library isn't available). */
export const iconFor = (name: IconName): LucideIcon =>
	ICON_COMPONENTS[(ICON_ALIASES[name] ?? name) as CuratedIconName] ?? Lightbulb;
