// Arabic search words mapped to the English words Lucide's icon tags use, so the icon picker can
// be searched in Arabic. Keys are written without the "ال" prefix; the search strips it.
const AR_TO_EN: Record<string, string[]> = {
	قلب: ['heart', 'cardiac'],
	نبض: ['pulse', 'heartbeat'],
	ضغط: ['blood pressure', 'pressure'],
	دم: ['blood', 'droplet'],
	سكر: ['sugar', 'candy', 'droplet'],
	سكري: ['droplet', 'blood'],
	دواء: ['pill', 'medicine', 'tablets'],
	دوا: ['pill', 'medicine', 'tablets'],
	علاج: ['medicine', 'pill', 'medical'],
	حبوب: ['pill', 'tablets'],
	برشام: ['pill', 'tablets'],
	حقنة: ['syringe', 'injection'],
	حقن: ['syringe', 'injection'],
	تطعيم: ['syringe', 'vaccine'],
	لقاح: ['syringe', 'vaccine'],
	حرارة: ['thermometer', 'temperature'],
	سخونية: ['thermometer', 'fever'],
	حمى: ['thermometer', 'fever'],
	برد: ['snowflake', 'cold'],
	انفلونزا: ['snowflake', 'thermometer', 'virus'],
	كحة: ['wind', 'lungs'],
	تنفس: ['wind', 'lungs', 'breath'],
	رئة: ['lungs', 'wind'],
	رئتين: ['lungs', 'wind'],
	مخ: ['brain'],
	دماغ: ['brain'],
	صداع: ['brain', 'headache'],
	عقل: ['brain', 'mind'],
	نفسية: ['brain', 'face-slightly-smiling', 'heart'],
	توتر: ['brain', 'stress', 'zap'],
	نوم: ['sleep', 'bed', 'moon'],
	سرير: ['bed'],
	راحة: ['bed', 'sleep', 'armchair'],
	ماء: ['water', 'glass-water', 'droplet'],
	مية: ['water', 'glass-water', 'droplet'],
	مياه: ['water', 'glass-water', 'droplet'],
	شرب: ['glass-water', 'drink', 'cup'],
	أكل: ['utensils', 'food'],
	طعام: ['utensils', 'food'],
	غذاء: ['utensils', 'food', 'salad'],
	اكل: ['utensils', 'food'],
	فاكهة: ['apple', 'fruit', 'banana'],
	خضار: ['carrot', 'salad', 'vegetable'],
	خضروات: ['carrot', 'salad', 'vegetable'],
	تفاح: ['apple'],
	جزر: ['carrot'],
	سمك: ['fish'],
	بيض: ['egg'],
	لبن: ['milk'],
	حليب: ['milk'],
	قهوة: ['coffee'],
	شاي: ['coffee', 'cup'],
	حلويات: ['candy', 'cake', 'cookie'],
	حلو: ['candy', 'cake'],
	خبز: ['wheat', 'croissant', 'sandwich'],
	عيش: ['wheat', 'sandwich'],
	قمح: ['wheat'],
	طفل: ['baby', 'child'],
	أطفال: ['baby', 'child'],
	اطفال: ['baby', 'child'],
	رضيع: ['baby'],
	حمل: ['baby', 'pregnancy'],
	عظم: ['bone'],
	عظام: ['bone'],
	مفاصل: ['bone', 'person-standing'],
	عين: ['eye', 'vision'],
	عيون: ['eye', 'vision'],
	نظر: ['eye', 'glasses'],
	نظارة: ['glasses'],
	أذن: ['ear', 'hearing'],
	ودن: ['ear', 'hearing'],
	سمع: ['ear', 'hearing'],
	أسنان: ['face-slightly-smiling', 'toothbrush'],
	اسنان: ['face-slightly-smiling', 'toothbrush'],
	سنان: ['face-slightly-smiling', 'toothbrush'],
	ابتسامة: ['face-slightly-smiling', 'smile'],
	رياضة: ['dumbbell', 'sport', 'exercise'],
	تمارين: ['dumbbell', 'exercise'],
	مشي: ['footprints', 'walk'],
	جري: ['footprints', 'run'],
	دراجة: ['bike'],
	عجلة: ['bike'],
	وزن: ['scale', 'weight'],
	سمنة: ['scale', 'weight'],
	رجيم: ['salad', 'scale', 'diet'],
	دايت: ['salad', 'scale', 'diet'],
	تدخين: ['cigarette', 'smoking'],
	سجاير: ['cigarette', 'smoking'],
	سيجارة: ['cigarette', 'smoking'],
	كحول: ['wine', 'beer'],
	وقت: ['clock', 'time', 'timer'],
	ساعة: ['clock', 'watch', 'timer'],
	يوم: ['calendar', 'day', 'sun'],
	تقويم: ['calendar'],
	موعد: ['calendar', 'clock'],
	تحذير: ['triangle-alert', 'warning', 'alert'],
	خطر: ['triangle-alert', 'danger', 'alert'],
	ممنوع: ['ban', 'forbidden'],
	صح: ['check', 'circle-check'],
	خطأ: ['x', 'circle-x'],
	غلط: ['x', 'circle-x'],
	سؤال: ['circle-question-mark', 'question'],
	فكرة: ['lightbulb', 'idea'],
	نصيحة: ['lightbulb', 'tip'],
	معمل: ['flask', 'microscope', 'lab'],
	مختبر: ['flask', 'microscope', 'lab'],
	تحليل: ['microscope', 'test-tube', 'flask'],
	تحاليل: ['microscope', 'test-tube', 'flask'],
	جينات: ['dna'],
	وراثة: ['dna'],
	جرح: ['bandage', 'wound'],
	إسعاف: ['ambulance', 'siren'],
	اسعاف: ['ambulance', 'siren'],
	طوارئ: ['ambulance', 'siren', 'emergency'],
	مستشفى: ['hospital'],
	عيادة: ['hospital', 'stethoscope', 'building'],
	طبيب: ['stethoscope', 'doctor'],
	دكتور: ['stethoscope', 'doctor'],
	دكتورة: ['stethoscope', 'doctor'],
	ممرضة: ['stethoscope', 'syringe'],
	رعاية: ['hand-heart', 'heart-handshake', 'care'],
	عائلة: ['users', 'family'],
	اسرة: ['users', 'family'],
	ناس: ['users', 'people'],
	شخص: ['user', 'person-standing'],
	جراثيم: ['bug', 'virus', 'bacteria'],
	فيروس: ['bug', 'virus'],
	بكتيريا: ['bug', 'bacteria', 'microscope'],
	عدوى: ['biohazard', 'bug', 'virus'],
	هواء: ['wind', 'air'],
	طبيعي: ['leaf', 'nature'],
	أعشاب: ['leaf', 'sprout', 'herb'],
	اعشاب: ['leaf', 'sprout', 'herb'],
	حرق: ['flame', 'burn'],
	التهاب: ['flame', 'inflammation'],
	شتاء: ['snowflake', 'winter'],
	شتا: ['snowflake', 'winter'],
	صيف: ['sun', 'summer'],
	شمس: ['sun'],
	طاقة: ['zap', 'battery', 'energy'],
	تعب: ['battery-low', 'fatigue'],
	إرهاق: ['battery-low', 'fatigue'],
	ارهاق: ['battery-low', 'fatigue'],
	بشرة: ['sparkles', 'skin'],
	جلد: ['sparkles', 'skin', 'hand'],
	نظافة: ['sparkles', 'clean', 'hand'],
	يد: ['hand'],
	إيد: ['hand'],
	ايد: ['hand'],
	غسيل: ['hand', 'droplets', 'wash'],
	قناع: ['shield', 'mask'],
	مناعة: ['shield-check', 'shield', 'immune'],
	حماية: ['shield-check', 'shield'],
	سعادة: ['face-slightly-smiling', 'laugh', 'heart'],
	حزن: ['frown', 'cloud-rain'],
	قلق: ['brain', 'frown'],
	موبايل: ['smartphone'],
	تليفون: ['smartphone', 'phone'],
	شاشة: ['monitor', 'smartphone'],
	كتاب: ['book'],
	قراءة: ['book-open'],
	منزل: ['house', 'home'],
	بيت: ['house', 'home'],
	عربية: ['car'],
	سيارة: ['car'],
};

/** The English words to search for, given a query that may be in Arabic. */
export const iconSearchTerms = (query: string): string[] => {
	const q = query.trim().toLowerCase();
	if (!q) return [];
	if (!/[\p{Script=Arabic}]/u.test(q)) return [q];
	const terms = new Set<string>();
	for (const raw of q.split(/\s+/)) {
		const word = raw.replace(/[^\p{L}]/gu, '');
		const bare = word.startsWith('ال') ? word.slice(2) : word;
		for (const key of [word, bare, bare.replace(/ة$/, 'ه'), bare.replace(/ه$/, 'ة')]) {
			for (const en of AR_TO_EN[key] ?? []) terms.add(en);
		}
	}
	return [...terms];
};
